### PR TITLE
feat: add fan scripts using raspberry pi hardware pwm

### LINKED ISSUE #8: These scripts are not using raspberry pi's hardware pwm causing high-ish cpu load
Raspberry PI supports hardware pwm, but the scripts in this repo are using software pwm causing a continuous cpu load of around 6%

### PR DESCRIPTION
**Pull request by pimlie**
Resolves: #8 

To install, first add `dtoverlay=pwm-2chan` to `/boot/config.txt` under `[all]` and reboot

Then
```
$ mv x-c1-fan.sh /usr/local/bin
$ chmod +x /usr/local/bin/x-c1-fan.sh
$ mv x-c1-fan.service /lib/systemd/system
$ systemctl daemon-reload
$ systemctl enable x-c1-fan
$ systemctl start x-c1-fan
```

### CODE REVIEW

**Comment by geekworm-com** [comment]
Thanks for your submission, I tested it out today and found some issues:
1. x-c1-fan.service has started, but the fan is **NOT** running.
2. The error output is as follows:

> pi@raspberrypi:~ $ sudo systemctl status x-c1-fan.service 
● x-c1-fan.service - Daemon to monitor and control fan speed
     Loaded: loaded (/lib/systemd/system/x-c1-fan.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-07-11 19:03:00 CST; 6min ago
   Main PID: 451 (bash)
      Tasks: 2 (limit: 1599)
        CPU: 511ms
     CGroup: /system.slice/x-c1-fan.service
             ├─ 451 bash /usr/local/bin/x-c1-fan.sh
             └─1594 sleep 30
>
> Jul 11 19:03:00 raspberrypi systemd[1]: Started Daemon to monitor and control fan speed.
> Jul 11 19:03:00 raspberrypi x-c1-fan.sh[451]: /usr/local/bin/x-c1-fan.sh: line 87: echo: write error: Invalid argument
> Jul 11 19:03:00 raspberrypi x-c1-fan.sh[451]: Fan speed change to 50, temp is 53.56

**Comment by pimlie** [comment]
@geekworm-com Could you please change to `SHOW_DEBUG=1` on line 8 and check the logs what value is being calculated for the duty cycle?

Also for testing/debugging it might be easier to run the script manually, ie just run `x-c1-fan.sh` directly in the console instead of going through systemd :)

**Comment by geekworm-com** [comment]
> @geekworm-com Could you please change to `SHOW_DEBUG=1` on line 8 and check the logs what value is being calculated for the duty cycle?
> 
> Also for testing/debugging it might be easier to run the script manually, ie just run `x-c1-fan.sh` directly in the console instead of going through systemd :)

Yes, as following:
>pi@raspberrypi:~ $ sudo systemctl status x-c1-fan.service 
● x-c1-fan.service - Daemon to monitor and control fan speed
     Loaded: loaded (/lib/systemd/system/x-c1-fan.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-07-11 19:20:12 CST; 9min ago
   Main PID: 436 (bash)
      Tasks: 2 (limit: 1599)
        CPU: 666ms
     CGroup: /system.slice/x-c1-fan.service
             ├─ 436 bash /usr/local/bin/x-c1-fan.sh
             └─1626 sleep 30
>
> Jul 11 19:20:12 raspberrypi systemd[1]: Started Daemon to monitor and control fan speed.
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: f=2000, p=500000, dc=0
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: pwm_change_duty_cycle: 0 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: /usr/local/bin/x-c1-fan.sh: line 87: echo: write error: Invalid argument
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: pwm_change_frequency: 500000 > /sys/class/pwm/pwmchip0/pwm0/period
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: f=2000, p=500000, dc=0
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: pwm_change_duty_cycle: 0 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: f=2000, p=500000, dc=50
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: pwm_change_duty_cycle: 250000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
Jul 11 19:20:12 raspberrypi x-c1-fan.sh[436]: Fan speed change to 50, temp is 55.02
pi@raspberrypi:~ $ 

And I test it base '2023-05-03-raspios-bullseye-arm64.img.xz', I only use **x-c1-fan.service** and **x-c1-fan.sh**, I don't run **install.sh** from us.

**Comment by geekworm-com** [comment]
> @geekworm-com Could you please change to `SHOW_DEBUG=1` on line 8 and check the logs what value is being calculated for the duty cycle?
> 
> Also for testing/debugging it might be easier to run the script manually, ie just run `x-c1-fan.sh` directly in the console instead of going through systemd :)

And I run the script file **x-c1-fan.sh** manually, but the fan is still not running
>pi@raspberrypi:/usr/local/bin $ pwd
/usr/local/bin
pi@raspberrypi:/usr/local/bin $ sudo ./x-c1-fan.sh 
f=2000, p=500000, dc=0
pwm_change_duty_cycle: 0 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
pwm_change_frequency: 500000 > /sys/class/pwm/pwmchip0/pwm0/period
f=2000, p=500000, dc=0
pwm_change_duty_cycle: 0 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
f=2000, p=500000, dc=50
pwm_change_duty_cycle: 250000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
Fan speed change to 50, temp is 55.50

**Comment by geekworm-com** [comment]
@pimlie 
And I run the script file **x-c1-fan.sh** manually, but the fan is still **not** running
>pi@raspberrypi:/usr/local/bin $ pwd
/usr/local/bin
pi@raspberrypi:/usr/local/bin $ sudo ./x-c1-fan.sh 
f=2000, p=500000, dc=0
pwm_change_duty_cycle: 0 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
pwm_change_frequency: 500000 > /sys/class/pwm/pwmchip0/pwm0/period
f=2000, p=500000, dc=0
pwm_change_duty_cycle: 0 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
f=2000, p=500000, dc=50
pwm_change_duty_cycle: 250000 > /sys/class/pwm/pwmchip0/pwm0/duty_cycle
Fan speed change to 50, temp is 55.50

**Comment by pimlie** [comment]
@geekworm-com Yeah, I found the issue. Apparently I didn't test the script well after rebooting/debugging myself, seems we also have to `enable` the pwm channel to start it. Have a fix incoming, give me a few minutes to wrap it up :)

**Comment by pimlie** [comment]
@geekworm-com Please check the fix :)

**Comment by geekworm-com** [comment]
@pimlie 
Thanks for your kind help.

I tested your script and found it is fully usable on the OS below:

- Raspbian
- DietPi
- Manjaro
- Ubuntu
- myNode
- Umbrel
- Volumio
- RetroPie
- Twister

I merged your code into repository `xsript`: https://github.com/geekworm-com/xscript

**Comment by geekworm-com** [comment]
@pimlie 
Can you help me another question?

If we use GPIO13 (like [X735 V2.5 hardware](https://wiki.geekworm.com/X735_Hardware) or [X729 hardware](https://wiki.geekworm.com/X729-hardware)) to control PWM fan, can we use the same hardware PWM method?

I referrer to https://github.com/Pioreactor/rpi_hardware_pwm, and try to add the following into config.txt, but the pwn fan is not running.
~~~
dtoverlay=pwm-2chan,pin=12,func=4,pin2=13,func2=4
~~~
or
~~~
dtoverlay=pwm-2chan,pin2=13,func2=4
~~~

After the device is rebooted, run the `lsmod | grep pwm`  and the result as following:
<pre>pwm_bcm2835            16384  1</pre>

And  the path `/sys/class/pwm/pwmchip0` can also be found.

Thanks in advance~

**Comment by pimlie** [comment]
@geekworm-com As I dont have a X729 or X735 I cannot try myself, but I believe that if you add those `dtoverlay`'s you mentioned above then pin 12 would be channel 0 and pin 13 would be channel 1.

So my guess is that you only have to change `PWM_CHANNEL=1` on line 5 of the bash script to get it to work?

**Comment by geekworm-com** [comment]
@pimlie 
Thank you for your kind support, you solved a big problem for us. 

You are right, change `PWM_CHANNEL=1` then the pwm fan goes work

I updated the script guide for [X735](https://github.com/geekworm-com/x735-script)

Thank you again.

**Comment by geekworm-com** [comment]
@pimlie 
sorry to disturb you.
I'm a newbie to shell scripting.

Regarding the x-c1-fan.sh script, there is a new problem. When running in some OS environments such as **Home Assistant**, an error will occur at line 184 as follows:
~~~
printf -v CUR_TEMP %0.0f "$TEMP"  Return invalid Number
~~~

Bash shell version as follwing:
~~~
pi@raspberrypi:~ $ bash --version
GNU bash, versione 5.1.4(1)-release (arm-unknown-linux-gnueabihf)
Copyright (C) 2020 Free Software Foundation, Inc.
~~~

OS information as folloing:
~~~
raspberrypi 6.1.29-v8+ #1652 SMP PREEMPT Wed May 24 14:46:55 BST 2023 aarch64
~~~
My question is, is there a more compatible way to convert float to integer?

**Pull request merged**
